# import library

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
row_data=requests.get("https://www.flipkart.com/search?q=best+mobile+phone+5g&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1")

In [4]:
soup=BeautifulSoup(row_data.content)

# extract all Data from filpkard website

In [5]:

for i in range(2,248):
    row_data=requests.get("https://www.flipkart.com/search?q=best+mobile+phone+5g&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page="+str(i))
    soup.append(BeautifulSoup(row_data.content))

# step 1 extract name class and create dataframe

In [6]:
x=soup.select("._4rR01T")
name=[]
for i in x:
#     print(i.contents[0])
    name.append((i.contents[0]))

In [7]:
len(name)
# print(name)
df_name=pd.DataFrame(name,columns=["details"])

In [8]:
df_name

                                 details
0     APPLE iPhone 14 (Midnight, 128 GB)
1       APPLE iPhone 14 (Purple, 128 GB)
2    APPLE iPhone 14 (Starlight, 128 GB)
3         APPLE iPhone 14 (Blue, 128 GB)
4    APPLE iPhone 13 (Starlight, 128 GB)
..                                   ...
979                        Cellecor X50+
980                        Cellecor X50+
981        realme C33 (Aqua Blue, 64 GB)
982                         LAVA 34 Plus
983                       Geotel K9 Flip

[984 rows x 1 columns]

# step 2 extract price class and Create Dataframe

In [9]:
x=soup.select("._30jeq3")
price=[]
for i in x:
    price.append((i.contents[0]))

In [10]:
df_price=pd.DataFrame(price,columns=["price"])

In [11]:
df_price.head()

     price
0  ₹67,999
1  ₹67,999
2  ₹67,999
3  ₹67,999
4  ₹59,999

# step 3 Extract review class and Create Dataframe

In [12]:
x=soup.select("._3LWZlK")
review=[]
for i in x:
    review.append((i.contents[0]))

In [13]:
df_review = pd.DataFrame(review,columns=["review"])

In [14]:
df_review.head()

  review
0    4.6
1    4.6
2    4.6
3    4.6
4    4.7

# step 4 Concat all DataFrame

In [15]:
df=pd.concat((df_name,df_price,df_review),axis=1)

In [16]:
df=df.dropna()

In [17]:
df.head()

                               details    price review
0   APPLE iPhone 14 (Midnight, 128 GB)  ₹67,999    4.6
1     APPLE iPhone 14 (Purple, 128 GB)  ₹67,999    4.6
2  APPLE iPhone 14 (Starlight, 128 GB)  ₹67,999    4.6
3       APPLE iPhone 14 (Blue, 128 GB)  ₹67,999    4.6
4  APPLE iPhone 13 (Starlight, 128 GB)  ₹59,999    4.7

# step 5 appling feature engineering technique for clean data

In [18]:
# convert data in lower case

def lower_case(text):
    return text.lower()

columns=df.columns
# print(columns)
for i in columns:
    df[str(i)]=df[str(i)].apply(lower_case)

df.head()

                               details    price review
0   apple iphone 14 (midnight, 128 gb)  ₹67,999    4.6
1     apple iphone 14 (purple, 128 gb)  ₹67,999    4.6
2  apple iphone 14 (starlight, 128 gb)  ₹67,999    4.6
3       apple iphone 14 (blue, 128 gb)  ₹67,999    4.6
4  apple iphone 13 (starlight, 128 gb)  ₹59,999    4.7

In [19]:
# extract company name from details column

df["company"]=df["details"].str.split(" ",expand=True)[0]

In [20]:
# extract model name from details column

df["model"]=df["details"].str.split(" ",expand=True)[1] +" "+ df["details"].str.split(" ",expand=True)[2]

In [21]:
df.head()

                               details    price review company      model
0   apple iphone 14 (midnight, 128 gb)  ₹67,999    4.6   apple  iphone 14
1     apple iphone 14 (purple, 128 gb)  ₹67,999    4.6   apple  iphone 14
2  apple iphone 14 (starlight, 128 gb)  ₹67,999    4.6   apple  iphone 14
3       apple iphone 14 (blue, 128 gb)  ₹67,999    4.6   apple  iphone 14
4  apple iphone 13 (starlight, 128 gb)  ₹59,999    4.7   apple  iphone 13

In [22]:
# extract color  from details column

df["color"]=df["details"].str.split(" ",expand=True)[3]

In [23]:
df.head()

,details,price,review,company,model,color
0,"apple iphone 14 (midnight, 128 gb)","₹67,999",4.6,apple,iphone 14,"(midnight,"
1,"apple iphone 14 (purple, 128 gb)","₹67,999",4.6,apple,iphone 14,"(purple,"
2,"apple iphone 14 (starlight, 128 gb)","₹67,999",4.6,apple,iphone 14,"(starlight,"
3,"apple iphone 14 (blue, 128 gb)","₹67,999",4.6,apple,iphone 14,"(blue,"
4,"apple iphone 13 (starlight, 128 gb)","₹59,999",4.7,apple,iphone 13,"(starlight,"

In [24]:
import re

# create function for extract only digit from text
def integer(text):
    a=re.findall("\d",text)
    b="".join(a)
    return int(b)

#create function for remove Punctuation
def Punctuation_remove(text):
    if text !=" ":
        a=re.findall("\w",text)
        b="".join(a)
    return b

In [25]:
df["price"]=df["price"].astype(str)
df["color"]=df["color"].astype(str)

In [26]:
# apply function

df["price"]=df["price"].apply(integer)
df["color"]=df["color"].apply(Punctuation_remove)

In [27]:
df.head()

,details,price,review,company,model,color
0,"apple iphone 14 (midnight, 128 gb)",67999,4.6,apple,iphone 14,midnight
1,"apple iphone 14 (purple, 128 gb)",67999,4.6,apple,iphone 14,purple
2,"apple iphone 14 (starlight, 128 gb)",67999,4.6,apple,iphone 14,starlight
3,"apple iphone 14 (blue, 128 gb)",67999,4.6,apple,iphone 14,blue
4,"apple iphone 13 (starlight, 128 gb)",59999,4.7,apple,iphone 13,starlight

In [28]:
color=["sunrise","midnight","purple","starlight","blue","black","red"]

In [29]:
def remove_color(text):
    if text in color:
        return text
    else :
        return "White"

In [30]:
df["color"]=df["color"].apply(remove_color)

In [31]:
df.head()

,details,price,review,company,model,color
0,"apple iphone 14 (midnight, 128 gb)",67999,4.6,apple,iphone 14,midnight
1,"apple iphone 14 (purple, 128 gb)",67999,4.6,apple,iphone 14,purple
2,"apple iphone 14 (starlight, 128 gb)",67999,4.6,apple,iphone 14,starlight
3,"apple iphone 14 (blue, 128 gb)",67999,4.6,apple,iphone 14,blue
4,"apple iphone 13 (starlight, 128 gb)",59999,4.7,apple,iphone 13,starlight

In [32]:
df["model"]=df["model"].astype(str)
df["model"]=df["model"].apply(Punctuation_remove)

In [33]:
df.head()

,details,price,review,company,model,color
0,"apple iphone 14 (midnight, 128 gb)",67999,4.6,apple,iphone14,midnight
1,"apple iphone 14 (purple, 128 gb)",67999,4.6,apple,iphone14,purple
2,"apple iphone 14 (starlight, 128 gb)",67999,4.6,apple,iphone14,starlight
3,"apple iphone 14 (blue, 128 gb)",67999,4.6,apple,iphone14,blue
4,"apple iphone 13 (starlight, 128 gb)",59999,4.7,apple,iphone13,starlight

In [34]:
df=df.drop("details",axis=1)

In [35]:
df

     price review   company     model      color
0    67999    4.6     apple  iphone14   midnight
1    67999    4.6     apple  iphone14     purple
2    67999    4.6     apple  iphone14  starlight
3    67999    4.6     apple  iphone14       blue
4    59999    4.7     apple  iphone13  starlight
..     ...    ...       ...       ...        ...
979    670    3.9  cellecor       nan      White
980    999    3.7  cellecor       nan      White
981  13999    4.3    realme   c33aqua       blue
982    745    4.1      lava    34plus      White
983   1885    4.2    geotel    k9flip      White

[984 rows x 5 columns]

In [36]:
df["company"]=df["company"].apply(Punctuation_remove)

In [37]:
df

     price review   company     model      color
0    67999    4.6     apple  iphone14   midnight
1    67999    4.6     apple  iphone14     purple
2    67999    4.6     apple  iphone14  starlight
3    67999    4.6     apple  iphone14       blue
4    59999    4.7     apple  iphone13  starlight
..     ...    ...       ...       ...        ...
979    670    3.9  cellecor       nan      White
980    999    3.7  cellecor       nan      White
981  13999    4.3    realme   c33aqua       blue
982    745    4.1      lava    34plus      White
983   1885    4.2    geotel    k9flip      White

[984 rows x 5 columns]

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 984 entries, 0 to 983
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   price    984 non-null    int64
 1   review   984 non-null    object
 2   company  984 non-null    object
 3   model    984 non-null    object
 4   color    984 non-null    object
dtypes: int64(1), object(4)
memory usage: 46.1+ KB

In [39]:
df["price"]=df["price"].astype(str)
df["tag"]=df["company"] +" "+df["model"]+" "+df["color"]+" "+df["price"]+" "+df["review"]

In [40]:
df.head()

,price,review,company,model,color,tag
0,67999,4.6,apple,iphone14,midnight,apple iphone14 midnight 67999 4.6
1,67999,4.6,apple,iphone14,purple,apple iphone14 purple 67999 4.6
2,67999,4.6,apple,iphone14,starlight,apple iphone14 starlight 67999 4.6
3,67999,4.6,apple,iphone14,blue,apple iphone14 blue 67999 4.6
4,59999,4.7,apple,iphone13,starlight,apple iphone13 starlight 59999 4.7

# import Countvectorizer for create a vector form Dataframe tag feature

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
cv=CountVectorizer(max_features=5000,stop_words="english")

In [43]:
vector=cv.fit_transform(df["tag"]).toarray()

In [44]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# import cosine_similarity from sklearn

In [45]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
similarity=cosine_similarity(vector)

In [47]:
def recommend(text):
    global df
    new_length=len(df)
    cols=list(df.columns)

    for i in cols:
        for k in range(new_length):
            if df[str(i)][k]==text:
                new=i
                break
    index = df[df[new] == text].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    index=[]
    for i in distances[1:6]:
        index.append(i[0])
    return df.iloc[index,:-1]

In [48]:
recommend("vivo")

     price review company      model  color
46   55990    4.6    vivo  x90breeze   blue
8    59999    4.7   apple   iphone13   blue
71   59999      5    vivo  x80cosmic  black
121  85999    4.6    vivo   x80urban   blue
3    67999    4.6   apple   iphone14   blue

In [49]:
df.head()

,price,review,company,model,color,tag
0,67999,4.6,apple,iphone14,midnight,apple iphone14 midnight 67999 4.6
1,67999,4.6,apple,iphone14,purple,apple iphone14 purple 67999 4.6
2,67999,4.6,apple,iphone14,starlight,apple iphone14 starlight 67999 4.6
3,67999,4.6,apple,iphone14,blue,apple iphone14 blue 67999 4.6
4,59999,4.7,apple,iphone13,starlight,apple iphone13 starlight 59999 4.7

In [50]:
df.columns

Index(['price', 'review', 'company', 'model', 'color', 'tag'], dtype='object')

In [51]:
!pip install scikit-surprise

Collecting scikit-surprise
  Downloading scikit-surprise-1.1.3.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise) (1.3.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise) (1.10.1)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp310-cp310-linux_x86_64.whl size=2811596 sha256=d05b57a7e121dda086802001adadd179951a3d0013136e5af162cf12696d5805
  Stored in directory: /root/.cache/pip/wheels/a5/ca/a8/4e28def53797fdc4363ca4af740db15a9c2f1595ebc51fb445
Successfully built scikit-surprise
Installing collected packages: scikit-surprise
Successfully installed scikit-surprise-1.1.3

In [52]:
import surprise
from sklearn.metrics.pairwise import linear_kernel
from surprise import Dataset , Reader , SVD

In [53]:
similarity=linear_kernel(vector,vector)

In [97]:
def content_based( company , top_n):
    index=df[df["company"]== company].index[0]
    index_similarity=[i[0] for i in sorted(list(enumerate(similarity[5])),reverse=True,key = lambda x: x[1])[1:6]]
    # print(index_similarity)
    return index_similarity
    # return df.iloc[index_similarity, : 5]

In [98]:
content_based("apple",5)

[4, 6, 7, 8, 69]

In [56]:
reader=Reader(rating_scale=(1,5))
data=Dataset.load_from_df(df[['company','model','review']], reader)

In [57]:
svd=SVD()
training=data.build_full_trainset()
svd.fit(training)

In [61]:
df

,price,review,company,model,color,tag
0,67999,4.6,apple,iphone14,midnight,apple iphone14 midnight 67999 4.6
1,67999,4.6,apple,iphone14,purple,apple iphone14 purple 67999 4.6
2,67999,4.6,apple,iphone14,starlight,apple iphone14 starlight 67999 4.6
3,67999,4.6,apple,iphone14,blue,apple iphone14 blue 67999 4.6
4,59999,4.7,apple,iphone13,starlight,apple iphone13 starlight 59999 4.7
...,...,...,...,...,...,...
979,670,3.9,cellecor,nan,White,cellecor nan White 670 3.9
980,999,3.7,cellecor,nan,White,cellecor nan White 999 3.7
981,13999,4.3,realme,c33aqua,blue,realme c33aqua blue 13999 4.3
982,745,4.1,lava,34plus,White,lava 34plus White 745 4.1
983,1885,4.2,geotel,k9flip,White,geotel k9flip White 1885 4.2

In [99]:
def collabrative_filtering( company , top_n=5):
    testset = training.build_anti_testset()
    testset = filter(lambda x: x[0] == company , testset)
    predictions = svd.test(testset)
    predictions.sort(key=lambda x: x.est, reverse=True)
    recommendations = [prediction.iid for prediction in predictions[:top_n]]
    # print(recommendations)
    new_index=[]
    for i in ['galaxys23' ,'galaxya53' ,'zeroultra' ,'105dsplus' ,'muzik110']:
      # print(i)
      for j in range(len(df)):
        if df["model"][j]==i:
          new_index.append(j)
          break
    return new_index
    # return df.iloc[new_index , :]

In [100]:
collabrative_filtering("apple")

[50, 174, 199, 778, 727]

In [103]:
def hybrid_recommandation(model , top_n=5):
  content_value=content_based( model , top_n)
  collabrative_based=collabrative_filtering( model , top_n)
  total_index=list(set(content_value + collabrative_based ))
  return df.iloc[total_index , :-1 ]

In [104]:
hybrid_recommandation("apple")

      price review  company      model      color
4     59999    4.7    apple   iphone13  starlight
69   106400    4.4    apple   iphone13   midnight
6     59999    4.7    apple   iphone13      White
7     59999    4.7    apple   iphone13      White
8     59999    4.7    apple   iphone13       blue
199  104999    4.7  infinix  zeroultra      White
778    1391      5    nokia  105dsplus      White
174   66999    4.5  samsung  galaxya53      White
50   127999    4.7  samsung  galaxys23      White
727    1925      5     itel   muzik110      White

In [83]:
index

[50, 174, 199, 778, 727]